# -*- coding: utf-8 -*-
"""AADT-Crash Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g9Uj1BpT5DXswof4pXza6u5Ky4LPSeQe

METRO MANILA ROAD CRASH ANALYSIS: Traffic Volume vs Crashes
=============================================================================

Research Question: Does traffic volume increase crashes on major Metro Manila roads?

Dataset:
- Roads: 7 major Metro Manila roads (EDSA, C-5, Commonwealth, Quezon Ave,
         Roxas Blvd, Marcos Highway, Radial Road 10)
- Period: 2019-2024 (72 months)
- Observations: 504 monthly records (7 roads × 6 years × 12 months)
- Source: MMDA MMARAS Annual Reports

Author: Jerdan L. Gondayao, Johnmer M. Tanqui-on
"""

# CELL 1
# Data manipulation
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from pathlib import Path

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.dates as mdates

# Statistical analysis
from scipy import stats
from scipy.stats import pearsonr, spearmanr
import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.tsa.statespace.sarimax import SARIMAX

# Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score


# Warnings
import warnings
warnings.filterwarnings('ignore')

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.float_format', lambda x: '%.2f' % x)

# Plotting style
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

# Set random seed
np.random.seed(42)

# CELL 2
# =============================================================================
# CONFIGURATION & HELPER FUNCTIONS
# =============================================================================

COLORS = {
    'EDSA': '#94A5A6', 'C-5 Road': '#4ECDC4', 'Commonwealth Avenue': '#45B7D1',
    'Quezon Avenue': '#FFA07A', 'Roxas Boulevard': '#98D8C8',
    'Marcos Highway': '#F7DC6F', 'Radial Road 10': '#BB8FCE',
    'primary': '#2C3E50', 'secondary': '#E74C3C'
}

def print_section(title):
    print("\n" + "="*70 + f"\n {title}\n" + "="*70 + "\n")

def get_road_color(road_name):
    return COLORS.get(road_name, '#95A5A6')

def run_sarima_forecast(y, exog=None, forecast_steps=24, title="Forecast", y_label="Value"):
    """Utility function to fit SARIMA and plot results."""
    model = SARIMAX(y, exog=exog, order=(1, 1, 1), seasonal_order=(1, 1, 1, 12),
                    enforce_stationarity=False, enforce_invertibility=False)
    results = model.fit(disp=False)

    last_date = y.index[-1]
    forecast_dates = pd.date_range(start=last_date + pd.DateOffset(months=1), periods=forecast_steps, freq='MS')

    # Use last known exog values for forecast if provided
    exog_forecast = None
    if exog is not None:
        exog_forecast = pd.DataFrame({col: [exog[col].iloc[-1]] * forecast_steps for col in exog.columns}, index=forecast_dates)

    forecast = results.get_forecast(steps=forecast_steps, exog=exog_forecast)
    mean = forecast.predicted_mean
    ci = forecast.conf_int()

    fig, ax = plt.subplots(figsize=(14, 5))
    ax.plot(y.index, y, label='Historical', color='#2E86AB')
    ax.plot(mean.index, mean, label='Forecast', color='#E63946', linestyle='--')
    ax.fill_between(mean.index, ci.iloc[:, 0], ci.iloc[:, 1], color='#E63946', alpha=0.1)
    ax.axvline(x=last_date, color='gray', linestyle=':')
    ax.set_title(title, fontweight='bold')
    ax.set_ylabel(y_label)
    ax.legend()
    plt.show()
    return mean, ci


# CELL 3
# LOAD DATA

print_section("LOADING DATA")

from pathlib import Path

df = pd.read_csv(Path("dataset.csv"))

print("✓ Data loaded successfully!")
print(f"\nDataset shape: {df.shape[0]} rows × {df.shape[1]} columns")

# CELL 4
# INITIAL DATA SUMMARY REPORT

print_section("DATA ACQUISITION SUMMARY REPORT")

print("Dataset Characteristics:")
print(f"  • Total Observations: {len(df):,}")
print(f"  • Time Period: {df['year'].min()}-{df['year'].max()}")
print(f"  • Duration: {df['year'].max() - df['year'].min() + 1} years")
print(f"  • Monthly Data Points: {len(df) / df['road_name'].nunique():.0f} per road")
print(f"  • Roads Covered: {df['road_name'].nunique()}")

print("\n" + "-"*70)
print("Roads in Dataset (sorted by average AADT):")
print("-"*70)

# Create summary by road
road_summary = []
for road in df['road_name'].unique():
    road_data = df[df['road_name'] == road]
    road_summary.append({
        'Road': road,
        'Observations': len(road_data),
        'Avg AADT': road_data['aadt'].mean(),
        'Total Crashes': road_data['crashes_total'].sum(),
        'Fatal': road_data['crashes_fatal'].sum(),
        'Non-Fatal': road_data['crashes_non_fatal'].sum(),
        'Property': road_data['crashes_property'].sum(),
        'Avg Monthly Crashes': road_data['crashes_total'].mean()
    })

road_summary_df = pd.DataFrame(road_summary).sort_values('Avg AADT', ascending=False)

for idx, row in road_summary_df.iterrows():
    print(f"\n{row['Road']}")
    print(f"  • Observations: {int(row['Observations'])}")
    print(f"  • Avg AADT: {row['Avg AADT']:,.0f} vehicles/day")
    print(f"  • Total Crashes (2019-2024): {int(row['Total Crashes']):,}")
    print(f"    - Fatal: {int(row['Fatal'])}")
    print(f"    - Non-Fatal: {int(row['Non-Fatal']):,}")
    print(f"    - Property Damage: {int(row['Property']):,}")
    print(f"  • Avg Monthly Crash Reports: {row['Avg Monthly Crashes']:.1f}")

print("\n" + "-"*70)
print("Overall Statistics:")
print("-"*70)
print(f"  • Total Crashes (all roads, 2019-2024): {df['crashes_total'].sum():,}")
print(f"  • Total Fatal Crashes: {df['crashes_fatal'].sum():,}")
print(f"  • Total Non-Fatal Crashes: {df['crashes_non_fatal'].sum():,}")
print(f"  • Total Property Damage: {df['crashes_property'].sum():,}")
print(f"  • Average Monthly Crashes (per road): {df['crashes_total'].mean():.1f}")
print(f"  • Average AADT (all roads): {df['aadt'].mean():,.0f} vehicles/day")

print("\n" + "-"*70)
print("Crash Severity Breakdown:")
print("-"*70)
total_crashes = df['crashes_total'].sum()
print(f"  • Fatal: {df['crashes_fatal'].sum():,} ({df['crashes_fatal'].sum()/total_crashes*100:.1f}%)")
print(f"  • Non-Fatal Injury: {df['crashes_non_fatal'].sum():,} ({df['crashes_non_fatal'].sum()/total_crashes*100:.1f}%)")
print(f"  • Property Damage Only: {df['crashes_property'].sum():,} ({df['crashes_property'].sum()/total_crashes*100:.1f}%)")


# CELL 5
# AADT TRENDS OVER TIME (2019-2024) - SEPARATE GRAPHS PER ROAD

print_section("TRAFFIC VOLUME ANALYSIS: AADT Trends")

df_yearly = df.groupby(['road_name', 'year'])['aadt'].first().reset_index()

roads_sorted = df.groupby('road_name')['aadt'].mean().sort_values(ascending=False).index

print("AADT by Year for Each Road:")
print("-" * 70)
for road in roads_sorted:
    road_data = df_yearly[df_yearly['road_name'] == road].sort_values('year')
    print(f"\n{road}:")
    for _, row in road_data.iterrows():
        print(f"  {row['year']} - {int(row['aadt']):,}")

print("\n")

fig, axes = plt.subplots(4, 2, figsize=(14, 12))

for idx, road in enumerate(roads_sorted):
    row = idx // 2
    col = idx % 2
    ax = axes[row, col]

    road_data = df_yearly[df_yearly['road_name'] == road].sort_values('year')

    ax.plot(road_data['year'],
            road_data['aadt'],
            color=get_road_color(road),
            linewidth=2.5,
            marker='o',
            markersize=6)

    ax.set_title(f'{road}', fontsize=11, fontweight='bold')
    ax.set_xlabel('Year', fontsize=9)
    ax.set_ylabel('AADT', fontsize=9)
    ax.grid(True, alpha=0.3, linestyle='--')
    ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{int(x):,}'))
    ax.set_xticks(road_data['year'])

axes[3, 1].axis('off')

fig.suptitle('Traffic Volume Trends on Major Metro Manila Roads (2019-2024)',
             fontsize=14, fontweight='bold')

plt.tight_layout()
plt.show()

print("\nAADT Summary Statistics by Road:")
print("-" * 70)
aadt_summary = df.groupby('road_name')['aadt'].agg(['mean', 'min', 'max', 'std'])
aadt_summary.columns = ['Average AADT', 'Min AADT', 'Max AADT', 'Std Dev']
aadt_summary = aadt_summary.sort_values('Average AADT', ascending=False)
print(aadt_summary.to_string())

# CELL 6
# TOTAL CRASH TRENDS OVER TIME (2019-2024) - SEPARATE GRAPHS PER ROAD

print_section("CRASH ANALYSIS: Total Crash Trends")

df_yearly_crashes = df.groupby(['road_name', 'year'])['crashes_total'].sum().reset_index()

roads_sorted = df.groupby('road_name')['crashes_total'].sum().sort_values(ascending=False).index

print("Total Crashes by Year for Each Road:")
print("-" * 70)
for road in roads_sorted:
    road_data = df_yearly_crashes[df_yearly_crashes['road_name'] == road].sort_values('year')
    print(f"\n{road}:")
    for _, row in road_data.iterrows():
        print(f"  {row['year']} - {int(row['crashes_total']):,}")

print("\n")

fig, axes = plt.subplots(4, 2, figsize=(14, 12))

for idx, road in enumerate(roads_sorted):
    row = idx // 2
    col = idx % 2
    ax = axes[row, col]

    road_data = df_yearly_crashes[df_yearly_crashes['road_name'] == road].sort_values('year')

    ax.plot(road_data['year'],
            road_data['crashes_total'],
            color=get_road_color(road),
            linewidth=2.5,
            marker='o',
            markersize=6)

    ax.set_title(f'{road}', fontsize=11, fontweight='bold')
    ax.set_xlabel('Year', fontsize=9)
    ax.set_ylabel('Total Crashes', fontsize=9)
    ax.grid(True, alpha=0.3, linestyle='--')
    ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{int(x):,}'))
    ax.set_xticks(road_data['year'])

axes[3, 1].axis('off')

fig.suptitle('Total Crash Trends on Major Metro Manila Roads (2019-2024)',
             fontsize=14, fontweight='bold')

plt.tight_layout()
plt.show()

print("\nTotal Crashes Summary Statistics by Road:")
print("-" * 70)
crash_summary = df.groupby('road_name')['crashes_total'].agg(['sum', 'mean', 'min', 'max', 'std'])
crash_summary.columns = ['Total Crashes (6 years)', 'Avg Monthly', 'Min Monthly', 'Max Monthly', 'Std Dev']
crash_summary = crash_summary.sort_values('Total Crashes (6 years)', ascending=False)
print(crash_summary.to_string())

# CELL 7
# AADT vs TOTAL CRASHES RELATIONSHIP - SEPARATE GRAPHS PER ROAD

print_section("RELATIONSHIP ANALYSIS: AADT vs Total Crashes")

df_yearly_aadt = df.groupby(['road_name', 'year'])['aadt'].first().reset_index()
df_yearly_crashes = df.groupby(['road_name', 'year'])['crashes_total'].sum().reset_index()

df_yearly_combined = df_yearly_aadt.merge(df_yearly_crashes, on=['road_name', 'year'])

roads_sorted = df.groupby('road_name')['aadt'].mean().sort_values(ascending=False).index

fig, axes = plt.subplots(4, 2, figsize=(16, 14))

for idx, road in enumerate(roads_sorted):
    row = idx // 2
    col = idx % 2
    ax1 = axes[row, col]

    road_data = df_yearly_combined[df_yearly_combined['road_name'] == road].sort_values('year')

    color_aadt = get_road_color(road)
    ax1.plot(road_data['year'],
             road_data['aadt'],
             color=color_aadt,
             linewidth=2.5,
             marker='o',
             markersize=6,
             label='AADT')

    ax1.set_xlabel('Year', fontsize=9, fontweight='bold')
    ax1.set_ylabel('AADT (vehicles/day)', fontsize=9, fontweight='bold', color=color_aadt)
    ax1.tick_params(axis='y', labelcolor=color_aadt)
    ax1.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{int(x):,}'))
    ax1.set_xticks(road_data['year'])
    ax1.grid(True, alpha=0.3, linestyle='--')

    ax2 = ax1.twinx()
    color_crash = '#E74C3C'
    ax2.plot(road_data['year'],
             road_data['crashes_total'],
             color=color_crash,
             linewidth=2.5,
             marker='s',
             markersize=6,
             label='Total Crashes',
             linestyle='--')

    ax2.set_ylabel('Total Crashes', fontsize=9, fontweight='bold', color=color_crash)
    ax2.tick_params(axis='y', labelcolor=color_crash)
    ax2.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{int(x):,}'))

    ax1.set_title(f'{road}', fontsize=11, fontweight='bold')

    lines1, labels1 = ax1.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    ax1.legend(lines1 + lines2, labels1 + labels2, loc='upper left', fontsize=8)

axes[3, 1].axis('off')

fig.suptitle('AADT vs Total Crashes on Major Metro Manila Roads (2019-2024)',
             fontsize=15, fontweight='bold')

plt.tight_layout()
plt.show()

# CELL 8
# STATISTICAL ANALYSIS: AADT vs CRASHES RELATIONSHIP

print_section("RELATIONSHIP ANALYSIS: Does Higher AADT Lead to More Crashes?")

df_yearly_combined = df.groupby(['road_name', 'year']).agg({
    'aadt': 'first',
    'crashes_total': 'sum'
}).reset_index()

print("QUESTION 1: Across different roads, does higher AADT mean more crashes?")
print("-" * 70)

road_comparison = df.groupby('road_name').agg({
    'aadt': 'mean',
    'crashes_total': 'sum'
}).reset_index()
road_comparison.columns = ['Road', 'Avg AADT', 'Total Crashes (6 years)']
road_comparison = road_comparison.sort_values('Avg AADT', ascending=False)

print("\nRoad Rankings by Traffic Volume and Crashes:")
for idx, row in road_comparison.iterrows():
    print(f"{row['Road']:25} | Avg AADT: {int(row['Avg AADT']):>10,} | Total Crashes: {int(row['Total Crashes (6 years)']):>7,}")

# Calculate correlation across roads
corr_across_roads = road_comparison['Avg AADT'].corr(road_comparison['Total Crashes (6 years)'])
print(f"\nCorrelation between AADT and Total Crashes (across roads): {corr_across_roads:.3f}")

if corr_across_roads > 0.7:
    print("✓ STRONG POSITIVE correlation - Roads with higher traffic volume have significantly more crashes")
elif corr_across_roads > 0.4:
    print("✓ MODERATE POSITIVE correlation - Roads with higher traffic tend to have more crashes")
elif corr_across_roads > 0:
    print("✓ WEAK POSITIVE correlation - Higher traffic shows some association with more crashes")
else:
    print("✗ NO or NEGATIVE correlation - Higher traffic does not necessarily mean more crashes")

print("\n" + "=" * 70)
print("\nQUESTION 2: As AADT increases over time, do crashes also increase?")
print("-" * 70)

# Analyze time trends for each road
print("\nYear-over-Year Correlation Analysis (per road):")
print("-" * 70)

correlation_results = []
for road in df_yearly_combined['road_name'].unique():
    road_data = df_yearly_combined[df_yearly_combined['road_name'] == road].sort_values('year')

    corr = road_data['aadt'].corr(road_data['crashes_total'])
    correlation_results.append({'Road': road, 'Correlation': corr})

    aadt_2019 = road_data[road_data['year'] == 2019]['aadt'].values[0]
    aadt_2024 = road_data[road_data['year'] == 2024]['aadt'].values[0]
    crashes_2019 = road_data[road_data['year'] == 2019]['crashes_total'].values[0]
    crashes_2024 = road_data[road_data['year'] == 2024]['crashes_total'].values[0]

    aadt_change = ((aadt_2024 - aadt_2019) / aadt_2019) * 100
    crash_change = ((crashes_2024 - crashes_2019) / crashes_2019) * 100

    print(f"\n{road}:")
    print(f"  Correlation coefficient: {corr:.3f}")
    print(f"  AADT change (2019→2024): {aadt_change:+.1f}%")
    print(f"  Crash change (2019→2024): {crash_change:+.1f}%")

    if corr > 0.5:
        print(f"  → Strong positive relationship - crashes tend to increase with AADT")
    elif corr > 0:
        print(f"  → Weak positive relationship - some alignment between AADT and crashes")
    elif corr > -0.5:
        print(f"  → Weak negative relationship - crashes decrease as AADT increases")
    else:
        print(f"  → Strong negative relationship - higher AADT associated with fewer crashes")

overall_corr = df_yearly_combined['aadt'].corr(df_yearly_combined['crashes_total'])
print("\n" + "=" * 70)
print(f"\nOVERALL CORRELATION (all roads, all years): {overall_corr:.3f}")

corr_df = pd.DataFrame(correlation_results)
avg_corr = corr_df['Correlation'].mean()
print(f"AVERAGE CORRELATION (across roads): {avg_corr:.3f}")

print("\n" + "=" * 70)
print("KEY FINDINGS:")
print("=" * 70)

if corr_across_roads > 0.5:
    print("\n1. ACROSS ROADS: YES - Higher traffic volume is associated with MORE crashes")
    print("   Roads with more vehicles tend to experience more crash incidents.")
else:
    print("\n1. ACROSS ROADS: WEAK/NO - Higher traffic volume doesn't strongly predict crashes")
    print("   Other factors besides traffic volume influence crash rates.")

if avg_corr > 0.3:
    print("\n2. OVER TIME: YES - As AADT increases, crashes tend to increase")
    print("   When traffic volume grows on a road, crash incidents typically rise.")
elif avg_corr > -0.3:
    print("\n2. OVER TIME: MIXED - Relationship varies by road")
    print("   Some roads show increases in crashes with higher traffic, others don't.")
else:
    print("\n2. OVER TIME: NO - As AADT increases, crashes tend to DECREASE")
    print("   Higher traffic volumes are associated with fewer crashes (possibly due to")
    print("   slower speeds or improved infrastructure).")


print("\n" + "=" * 70)

# CELL 9
# QUICK CRASH RATE TEST
print("=" * 80)
print("QUICK TEST: How does normalization change the rankings?")
print("=" * 80)

road_comparison = df.groupby('road_name').agg({
    'aadt': 'mean',
    'crashes_total': 'sum'
}).reset_index()

road_comparison['crash_rate_per_100k'] = (
    road_comparison['crashes_total'] / road_comparison['aadt']
) * 100000

print("\nRanking by TOTAL CRASHES:")
print(road_comparison.sort_values('crashes_total', ascending=False)[['road_name', 'crashes_total']])

print("\nRanking by CRASH RATE (per 100k AADT):")
print(road_comparison.sort_values('crash_rate_per_100k', ascending=False)[['road_name', 'crash_rate_per_100k']])

# CELL 10
# CRASH SEVERITY TRENDS OVER TIME (2019-2024) - SEPARATE GRAPHS PER ROAD

print_section("CRASH SEVERITY ANALYSIS: Fatal, Non-Fatal, and Property Damage Trends")

df_yearly_severity = df.groupby(['road_name', 'year']).agg({
    'crashes_fatal': 'sum',
    'crashes_non_fatal': 'sum',
    'crashes_property': 'sum'
}).reset_index()

roads_sorted = df.groupby('road_name')['crashes_total'].sum().sort_values(ascending=False).index

print("Crash Severity by Year for Each Road:")
print("-" * 70)
for road in roads_sorted:
    road_data = df_yearly_severity[df_yearly_severity['road_name'] == road].sort_values('year')
    print(f"\n{road}:")
    for _, row in road_data.iterrows():
        print(f"  {row['year']} - Fatal: {int(row['crashes_fatal']):>3} | Non-Fatal: {int(row['crashes_non_fatal']):>5,} | Property: {int(row['crashes_property']):>5,}")

print("\n")

fig, axes = plt.subplots(4, 2, figsize=(16, 14))

for idx, road in enumerate(roads_sorted):
    row = idx // 2
    col = idx % 2
    ax = axes[row, col]

    road_data = df_yearly_severity[df_yearly_severity['road_name'] == road].sort_values('year')

    ax.plot(road_data['year'],
            road_data['crashes_fatal'],
            color='#E74C3C',
            linewidth=2.5,
            marker='o',
            markersize=6,
            label='Fatal')

    ax.plot(road_data['year'],
            road_data['crashes_non_fatal'],
            color='#F39C12',
            linewidth=2.5,
            marker='s',
            markersize=6,
            label='Non-Fatal Injury')

    ax.plot(road_data['year'],
            road_data['crashes_property'],
            color='#3498DB',
            linewidth=2.5,
            marker='^',
            markersize=6,
            label='Property Damage')

    ax.set_title(f'{road}', fontsize=11, fontweight='bold')
    ax.set_xlabel('Year', fontsize=9)
    ax.set_ylabel('Number of Crashes', fontsize=9)
    ax.grid(True, alpha=0.3, linestyle='--')
    ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{int(x):,}'))
    ax.set_xticks(road_data['year'])
    ax.legend(loc='best', fontsize=8)

axes[3, 1].axis('off')

fig.suptitle('Crash Severity Trends on Major Metro Manila Roads (2019-2024)',
             fontsize=15, fontweight='bold')

plt.tight_layout()
plt.show()

print("\nCrash Severity Summary Statistics by Road (2019-2024):")
print("-" * 70)
severity_summary = df.groupby('road_name').agg({
    'crashes_fatal': 'sum',
    'crashes_non_fatal': 'sum',
    'crashes_property': 'sum',
    'crashes_total': 'sum'
}).reset_index()

severity_summary['Fatal %'] = (severity_summary['crashes_fatal'] / severity_summary['crashes_total'] * 100)
severity_summary['Non-Fatal %'] = (severity_summary['crashes_non_fatal'] / severity_summary['crashes_total'] * 100)
severity_summary['Property %'] = (severity_summary['crashes_property'] / severity_summary['crashes_total'] * 100)

severity_summary = severity_summary.sort_values('crashes_total', ascending=False)
severity_summary.columns = ['Road', 'Fatal', 'Non-Fatal', 'Property', 'Total', 'Fatal %', 'Non-Fatal %', 'Property %']

print(severity_summary.to_string(index=False))

# CELL 11
# AVERAGE CRASHES PER MONTH (JANUARY - DECEMBER) PER ROAD

print_section("AVERAGE CRASHES PER MONTH PER ROAD")

month_names = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
               'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

roads_sorted = df.groupby('road_name')['crashes_total'].sum().sort_values(ascending=False).index

print("Average Crashes per Month by Road (2019-2024):")
print("-" * 70)
for road in roads_sorted:
    road_data = df[df['road_name'] == road].groupby('month')['crashes_total'].mean().reset_index()
    print(f"\n{road}:")
    for _, row in road_data.iterrows():
        print(f"  {month_names[int(row['month'])-1]:10} - {row['crashes_total']:.1f} crashes")

print("\n")

fig, axes = plt.subplots(4, 2, figsize=(16, 14))

for idx, road in enumerate(roads_sorted):
    row = idx // 2
    col = idx % 2
    ax = axes[row, col]

    road_data = df[df['road_name'] == road].groupby('month')['crashes_total'].mean().reset_index()
    road_data = road_data.sort_values('month')

    bars = ax.bar(range(12),
                  road_data['crashes_total'],
                  color=get_road_color(road),
                  edgecolor='black',
                  linewidth=1.2)

    for i, (bar, value) in enumerate(zip(bars, road_data['crashes_total'])):
        ax.text(bar.get_x() + bar.get_width()/2,
                bar.get_height() + max(road_data['crashes_total']) * 0.02,
                f'{value:.0f}',
                ha='center',
                va='bottom',
                fontweight='bold',
                fontsize=8)

    ax.set_title(f'{road}', fontsize=11, fontweight='bold')
    ax.set_xlabel('Month', fontsize=9)
    ax.set_ylabel('Avg Crashes', fontsize=9)
    ax.set_xticks(range(12))
    ax.set_xticklabels(month_names, rotation=45, ha='right', fontsize=8)
    ax.grid(axis='y', alpha=0.3, linestyle='--')

axes[3, 1].axis('off')

fig.suptitle('Average Monthly Crash Patterns by Road (2019-2024)',
             fontsize=15, fontweight='bold')

plt.tight_layout()
plt.show()

# CELL 12
# MOST DANGEROUS ROAD PER MONTH ANALYSIS - HEATMAP

print_section("MOST DANGEROUS ROAD PER MONTH")

month_names = ['January', 'February', 'March', 'April', 'May', 'June',
               'July', 'August', 'September', 'October', 'November', 'December']
month_names_short = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                     'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

monthly_road_crashes = df.groupby(['month', 'road_name'])['crashes_total'].mean().reset_index()


fig, ax = plt.subplots(figsize=(14, 6))

pivot_data = monthly_road_crashes.pivot(index='road_name', columns='month', values='crashes_total')
pivot_data.columns = month_names_short

pivot_data['Total'] = pivot_data.sum(axis=1)
pivot_data = pivot_data.sort_values('Total', ascending=False).drop('Total', axis=1)

im = ax.imshow(pivot_data.values, cmap='YlOrRd', aspect='auto')

ax.set_xticks(range(12))
ax.set_xticklabels(month_names_short)
ax.set_yticks(range(len(pivot_data)))
ax.set_yticklabels(pivot_data.index)

for i in range(len(pivot_data)):
    for j in range(12):
        text = ax.text(j, i, f'{pivot_data.values[i, j]:.0f}',
                       ha="center", va="center", color="black", fontsize=8, fontweight='bold')

ax.set_title('Crash Heatmap: All Roads Across All Months (2019-2024)', fontsize=14, fontweight='bold', pad=15)
ax.set_xlabel('Month', fontsize=12, fontweight='bold')
ax.set_ylabel('Road', fontsize=12, fontweight='bold')

cbar = plt.colorbar(im, ax=ax)
cbar.set_label('Average Crashes', rotation=270, labelpad=20, fontweight='bold')

plt.tight_layout()
plt.show()

# CELL 13
# =============================================================================
# FEATURE ENGINEERING (Enhanced)
# =============================================================================

print_section("FEATURE ENGINEERING")

FORECAST_MONTHS = 24
last_date = pd.to_datetime(f"{df['year'].max()}-{df['month'].max():02d}-01")
forecast_dates = pd.date_range(start=last_date + pd.DateOffset(months=1),
                               periods=FORECAST_MONTHS, freq='MS')

df_ml = df.copy()
df_ml['date'] = pd.to_datetime(df_ml[['year', 'month']].assign(day=1))
df_ml = df_ml.sort_values(['road_name', 'date']).reset_index(drop=True)

# Cyclical month features
df_ml['month_sin'] = np.sin(2 * np.pi * df_ml['month'] / 12)
df_ml['month_cos'] = np.cos(2 * np.pi * df_ml['month'] / 12)

# Crash rates (normalized by traffic volume)
df_ml['crash_rate_per_100k'] = (df_ml['crashes_total'] / df_ml['aadt']) * 100000
df_ml['is_pandemic'] = df_ml['year'].isin([2020, 2021]).astype(int)

# Lag features (per road)
for lag in [1, 3, 6, 12]:
    df_ml[f'crashes_lag_{lag}'] = df_ml.groupby('road_name')['crashes_total'].shift(lag)

# Rolling means (per road)
df_ml['crashes_rolling_3'] = df_ml.groupby('road_name')['crashes_total'].transform(
    lambda x: x.rolling(3, min_periods=1).mean()
)
df_ml['crashes_rolling_6'] = df_ml.groupby('road_name')['crashes_total'].transform(
    lambda x: x.rolling(6, min_periods=1).mean()
)

# Year-over-year change
df_ml['yoy_change'] = df_ml.groupby('road_name')['crashes_total'].pct_change(12)

# Severity ratios
df_ml['fatal_ratio'] = df_ml['crashes_fatal'] / df_ml['crashes_total'].clip(lower=1)
df_ml['nonfatal_ratio'] = df_ml['crashes_non_fatal'] / df_ml['crashes_total'].clip(lower=1)

# Fill NaN from lag/rolling with 0
df_ml = df_ml.fillna(0)

print("✓ Features engineered:")
print("  • Cyclical: month_sin, month_cos")
print("  • Lag features: crashes_lag_1, _3, _6, _12")
print("  • Rolling means: crashes_rolling_3, _6")
print("  • Rates: crash_rate_per_100k, fatal_ratio, nonfatal_ratio")
print("  • Contextual: is_pandemic, yoy_change")
print(f"\n  Total features available: {df_ml.shape[1]} columns")
print(f"  Forecast configuration: {FORECAST_MONTHS} months (2025-2026)")

# CELL 14
# =============================================================================
# PER-ROAD CRASH PREDICTION: Random Forest & Gradient Boosting
# =============================================================================

print_section("MACHINE LEARNING: Per-Road Crash Prediction")

FEATURES = ['aadt', 'month_sin', 'month_cos', 'is_pandemic',
            'crashes_lag_1', 'crashes_lag_3', 'crashes_lag_6', 'crashes_lag_12',
            'crashes_rolling_3', 'crashes_rolling_6', 'yoy_change']
TARGET = 'crashes_total'

ml_results = {}
feature_importances = {}

roads_sorted = sorted(df_ml['road_name'].unique())

for i, road in enumerate(roads_sorted, 1):
    print(f"\n[{i}/7] {road}")
    print("-" * 60)

    road_data = df_ml[df_ml['road_name'] == road].sort_values('date').copy()

    # Temporal split: 2019-2023 train, 2024 test
    train = road_data[road_data['year'] < 2024]
    test = road_data[road_data['year'] >= 2024]

    if len(train) < 12 or len(test) == 0:
        print("  ⚠ Insufficient data, skipping")
        continue

    X_train, y_train = train[FEATURES], train[TARGET]
    X_test, y_test = test[FEATURES], test[TARGET]

    # Scale features
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    road_results = {}

    # --- Random Forest ---
    rf = RandomForestRegressor(n_estimators=200, max_depth=8, random_state=42, n_jobs=-1)
    rf.fit(X_train_scaled, y_train)
    rf_pred = rf.predict(X_test_scaled)

    road_results['Random Forest'] = {
        'MAE': mean_absolute_error(y_test, rf_pred),
        'RMSE': np.sqrt(mean_squared_error(y_test, rf_pred)),
        'R2': r2_score(y_test, rf_pred),
        'predictions': rf_pred,
        'model': rf, 'scaler': scaler
    }

    # Store feature importances
    feature_importances[road] = dict(zip(FEATURES, rf.feature_importances_))

    # --- Gradient Boosting ---
    gb = GradientBoostingRegressor(n_estimators=200, max_depth=5, learning_rate=0.1, random_state=42)
    gb.fit(X_train_scaled, y_train)
    gb_pred = gb.predict(X_test_scaled)

    road_results['Gradient Boosting'] = {
        'MAE': mean_absolute_error(y_test, gb_pred),
        'RMSE': np.sqrt(mean_squared_error(y_test, gb_pred)),
        'R2': r2_score(y_test, gb_pred),
        'predictions': gb_pred,
        'model': gb, 'scaler': scaler
    }

    ml_results[road] = {'results': road_results, 'y_test': y_test, 'test_dates': test['date'].values}

    # Print results
    for model_name, metrics in road_results.items():
        print(f"  {model_name:20s} | MAE: {metrics['MAE']:7.1f} | RMSE: {metrics['RMSE']:7.1f} | R²: {metrics['R2']:6.3f}")

# --- Visualization: Actual vs Predicted per road ---
fig, axes = plt.subplots(4, 2, figsize=(16, 14))

for idx, road in enumerate(roads_sorted):
    row_i = idx // 2
    col_i = idx % 2
    ax = axes[row_i, col_i]

    if road not in ml_results:
        ax.axis('off')
        continue

    data = ml_results[road]
    dates = data['test_dates']
    actual = data['y_test'].values

    ax.plot(dates, actual, 'ko-', label='Actual', linewidth=2, markersize=5)
    for model_name, metrics in data['results'].items():
        ax.plot(dates, metrics['predictions'], '--', label=f'{model_name} (R²={metrics["R2"]:.2f})',
                linewidth=1.5, markersize=4, marker='s')

    ax.set_title(f'{road}', fontsize=11, fontweight='bold')
    ax.set_xlabel('Date', fontsize=9)
    ax.set_ylabel('Crashes', fontsize=9)
    ax.legend(fontsize=7, loc='best')
    ax.grid(True, alpha=0.3, linestyle='--')
    ax.tick_params(axis='x', rotation=45)

axes[3, 1].axis('off')
fig.suptitle('ML Models: Actual vs Predicted Crashes (2024 Test Set)', fontsize=15, fontweight='bold')
plt.tight_layout()
plt.show()

# CELL 15
# =============================================================================
# FEATURE IMPORTANCE ANALYSIS
# =============================================================================

print_section("FEATURE IMPORTANCE ANALYSIS")

fig, axes = plt.subplots(4, 2, figsize=(16, 14))

for idx, road in enumerate(roads_sorted):
    row_i = idx // 2
    col_i = idx % 2
    ax = axes[row_i, col_i]

    if road not in feature_importances:
        ax.axis('off')
        continue

    imp = feature_importances[road]
    sorted_imp = sorted(imp.items(), key=lambda x: x[1], reverse=True)
    names = [x[0] for x in sorted_imp]
    values = [x[1] for x in sorted_imp]

    bars = ax.barh(range(len(names)), values, color=get_road_color(road), edgecolor='black', linewidth=0.5)
    ax.set_yticks(range(len(names)))
    ax.set_yticklabels(names, fontsize=8)
    ax.set_title(f'{road}', fontsize=11, fontweight='bold')
    ax.set_xlabel('Importance', fontsize=9)
    ax.invert_yaxis()

axes[3, 1].axis('off')
fig.suptitle('Random Forest Feature Importance by Road', fontsize=15, fontweight='bold')
plt.tight_layout()
plt.show()

# Overall top features
print("\nTop 3 Most Important Features per Road:")
print("-" * 60)
for road in roads_sorted:
    if road not in feature_importances:
        continue
    imp = feature_importances[road]
    top3 = sorted(imp.items(), key=lambda x: x[1], reverse=True)[:3]
    features_str = ', '.join([f"{n} ({v:.3f})" for n, v in top3])
    print(f"  {road:25s} → {features_str}")

# CELL 16
# =============================================================================
# CRASH SEVERITY PREDICTION PER ROAD
# =============================================================================

print_section("CRASH SEVERITY PREDICTION PER ROAD")

SEVERITY_FEATURES = ['aadt', 'month_sin', 'month_cos', 'is_pandemic',
                     'crashes_lag_1', 'crashes_rolling_3', 'crashes_rolling_6']

severity_predictions = {}

for i, road in enumerate(roads_sorted, 1):
    print(f"\n[{i}/7] {road}")
    print("-" * 60)

    road_data = df_ml[df_ml['road_name'] == road].sort_values('date').copy()
    train = road_data[road_data['year'] < 2024]
    test = road_data[road_data['year'] >= 2024]

    if len(train) < 12 or len(test) == 0:
        continue

    road_severity = {}

    for severity, color_s in [('crashes_fatal', '#E74C3C'),
                                ('crashes_non_fatal', '#F39C12'),
                                ('crashes_property', '#3498DB')]:
        scaler_s = StandardScaler()
        X_tr = scaler_s.fit_transform(train[SEVERITY_FEATURES])
        X_te = scaler_s.transform(test[SEVERITY_FEATURES])

        gb_s = GradientBoostingRegressor(n_estimators=150, max_depth=4, learning_rate=0.1, random_state=42)
        gb_s.fit(X_tr, train[severity])
        pred_s = gb_s.predict(X_te)

        road_severity[severity] = {
            'actual': test[severity].values,
            'predicted': pred_s,
            'MAE': mean_absolute_error(test[severity], pred_s),
            'R2': r2_score(test[severity], pred_s) if test[severity].std() > 0 else 0
        }

        print(f"  {severity:22s} | MAE: {road_severity[severity]['MAE']:6.1f} | R²: {road_severity[severity]['R2']:6.3f}")

    severity_predictions[road] = road_severity

# Visualization: Severity predictions for top 3 highest-crash roads
top_roads = df.groupby('road_name')['crashes_total'].sum().sort_values(ascending=False).head(3).index

fig, axes = plt.subplots(3, 3, figsize=(18, 12))
severity_labels = {'crashes_fatal': 'Fatal', 'crashes_non_fatal': 'Non-Fatal', 'crashes_property': 'Property'}
severity_colors = {'crashes_fatal': '#E74C3C', 'crashes_non_fatal': '#F39C12', 'crashes_property': '#3498DB'}

for r_idx, road in enumerate(top_roads):
    if road not in severity_predictions:
        continue
    test_dates = df_ml[(df_ml['road_name'] == road) & (df_ml['year'] >= 2024)]['date'].values

    for s_idx, (sev, label) in enumerate(severity_labels.items()):
        ax = axes[r_idx, s_idx]
        data = severity_predictions[road][sev]
        ax.plot(test_dates, data['actual'], 'ko-', label='Actual', linewidth=2, markersize=5)
        ax.plot(test_dates, data['predicted'], '--', color=severity_colors[sev],
                label=f'Predicted (R²={data["R2"]:.2f})', linewidth=1.5, markersize=4, marker='s')
        ax.set_title(f'{road[:15]}... - {label}' if len(road) > 15 else f'{road} - {label}',
                     fontsize=10, fontweight='bold')
        ax.legend(fontsize=7)
        ax.grid(True, alpha=0.3, linestyle='--')
        ax.tick_params(axis='x', rotation=45)

fig.suptitle('Crash Severity Predictions: Top 3 Roads (2024 Test)', fontsize=15, fontweight='bold')
plt.tight_layout()
plt.show()

# CELL 17
# =============================================================================
# SARIMA FORECASTING PER ROAD (Fixed)
# =============================================================================

print_section("SARIMA FORECASTING: Per-Road (2025-2026)")

predictions_by_road = {}
sarima_eval = {}

for road in roads_sorted:
    road_data = df_ml[df_ml['road_name'] == road].set_index('date').sort_index()

    # Full model for forecasting
    y = road_data['crashes_total']
    exog = road_data[['aadt']]

    print(f"Forecasting {road}...")
    mean_fc, ci_fc = run_sarima_forecast(
        y, exog=exog,
        title=f"{road} - SARIMA Crash Forecast (2025-2026)",
        y_label="Total Crashes"
    )
    predictions_by_road[road] = {
        'forecast': mean_fc,
        'lower_ci': ci_fc.iloc[:, 0],
        'upper_ci': ci_fc.iloc[:, 1],
        'historical': y
    }

    # Evaluate on 2024 holdout
    train = road_data[road_data.index < '2024-01-01']
    test = road_data[road_data.index >= '2024-01-01']
    if len(train) > 0 and len(test) > 0:
        try:
            m = SARIMAX(train['crashes_total'], exog=train[['aadt']],
                        order=(1, 1, 1), seasonal_order=(1, 1, 1, 12),
                        enforce_stationarity=False, enforce_invertibility=False)
            res = m.fit(disp=False)
            pred = res.get_forecast(steps=len(test), exog=test[['aadt']]).predicted_mean
            sarima_eval[road] = {
                'MAE': mean_absolute_error(test['crashes_total'], pred),
                'RMSE': np.sqrt(mean_squared_error(test['crashes_total'], pred)),
                'R2': r2_score(test['crashes_total'], pred)
            }
        except:
            pass

# CELL 18
# =============================================================================
# MODEL COMPARISON: SARIMA vs Random Forest vs Gradient Boosting
# =============================================================================

print_section("MODEL COMPARISON: SARIMA vs ML Models")

comparison_rows = []
for road in roads_sorted:
    row_data = {'Road': road}

    # SARIMA metrics
    if road in sarima_eval:
        row_data['SARIMA_MAE'] = sarima_eval[road]['MAE']
        row_data['SARIMA_RMSE'] = sarima_eval[road]['RMSE']
        row_data['SARIMA_R2'] = sarima_eval[road]['R2']

    # ML metrics
    if road in ml_results:
        for model_name, metrics in ml_results[road]['results'].items():
            short = model_name.replace(' ', '_')
            row_data[f'{short}_MAE'] = metrics['MAE']
            row_data[f'{short}_RMSE'] = metrics['RMSE']
            row_data[f'{short}_R2'] = metrics['R2']

    comparison_rows.append(row_data)

comparison_df = pd.DataFrame(comparison_rows)

# Find best model per road
print("\nBest Model per Road (by lowest MAE on 2024 test set):")
print("-" * 70)

best_models = {}
for _, row in comparison_df.iterrows():
    road = row['Road']
    mae_cols = {c: row[c] for c in row.index if c.endswith('_MAE') and pd.notna(row[c])}
    if mae_cols:
        best_col = min(mae_cols, key=mae_cols.get)
        best_model = best_col.replace('_MAE', '').replace('_', ' ')
        best_mae = mae_cols[best_col]
        best_models[road] = best_model
        print(f"  {road:25s} → {best_model:20s} (MAE: {best_mae:.1f})")

# Visualization: MAE comparison bar chart
fig, ax = plt.subplots(figsize=(14, 7))

model_names_display = ['SARIMA', 'Random Forest', 'Gradient Boosting']
model_cols = ['SARIMA_MAE', 'Random_Forest_MAE', 'Gradient_Boosting_MAE']
colors_comp = ['#2E86AB', '#06A77D', '#E63946']

x = np.arange(len(roads_sorted))
width = 0.25

for i, (mcol, mname, mcolor) in enumerate(zip(model_cols, model_names_display, colors_comp)):
    if mcol in comparison_df.columns:
        vals = comparison_df[mcol].fillna(0).values
        ax.bar(x + i * width, vals, width, label=mname, color=mcolor, edgecolor='black', linewidth=0.5)

ax.set_xlabel('Road', fontsize=12, fontweight='bold')
ax.set_ylabel('Mean Absolute Error (MAE)', fontsize=12, fontweight='bold')
ax.set_title('Model Comparison: MAE on 2024 Test Set', fontsize=15, fontweight='bold')
ax.set_xticks(x + width)
ax.set_xticklabels([r[:12] + '...' if len(r) > 12 else r for r in roads_sorted], rotation=45, ha='right')
ax.legend(fontsize=11)
ax.grid(axis='y', alpha=0.3, linestyle='--')
plt.tight_layout()
plt.show()

# Full metrics table
print("\nFull Model Comparison (2024 Test Set):")
print("=" * 90)
print(comparison_df.to_string(index=False, float_format='%.2f'))

# CELL 19
# =============================================================================
# CRASH RISK SCORING & PEAK MONTH ANALYSIS
# =============================================================================

print_section("CRASH RISK SCORING & PEAK MONTHS (2025-2026)")

print("Objective: Identify the riskiest months for targeted interventions")
print("=" * 80)

# Compile SARIMA predictions
all_predictions = []
for road, data in predictions_by_road.items():
    forecast_data = pd.DataFrame({
        'date': data['forecast'].index,
        'road': road,
        'predicted_crashes': data['forecast'].values,
        'lower_ci': data['lower_ci'].values,
        'upper_ci': data['upper_ci'].values
    })
    forecast_data['year'] = forecast_data['date'].dt.year
    forecast_data['month'] = forecast_data['date'].dt.month
    all_predictions.append(forecast_data)

predictions_df = pd.concat(all_predictions, ignore_index=True)

# Peak months by road
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
          'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

for yr in [2025, 2026]:
    print(f"\nPEAK MONTHS BY ROAD ({yr})")
    print("-" * 70)
    peak = predictions_df[predictions_df['year'] == yr].groupby('road').apply(
        lambda x: x.loc[x['predicted_crashes'].idxmax()]
    ).reset_index(drop=True)

    for _, row in peak.iterrows():
        mname = months[int(row['month']) - 1]
        print(f"  {row['road']:25s} → {mname} {yr} ({row['predicted_crashes']:.0f} crashes)")

# Overall monthly risk rankings
print("\nOVERALL MONTHLY RISK RANKINGS (2025-2026)")
print("-" * 70)

monthly_totals = predictions_df.groupby('month')['predicted_crashes'].sum().sort_values(ascending=False)
for month_num, total in monthly_totals.items():
    mname = months[int(month_num) - 1]
    avg = total / 2 / 7
    print(f"  {mname:3s}: {avg:.0f} crashes/road (Total: {total:.0f})")

# Heatmap visualization
fig, axes = plt.subplots(1, 2, figsize=(18, 6))

for ax_i, yr in enumerate([2025, 2026]):
    heatmap_data = predictions_df[predictions_df['year'] == yr].pivot_table(
        index='road', columns='month', values='predicted_crashes', aggfunc='sum'
    )
    sns.heatmap(heatmap_data, annot=True, fmt='.0f', cmap='YlOrRd',
                cbar_kws={'label': 'Predicted Crashes'}, ax=axes[ax_i])
    axes[ax_i].set_title(f'{yr} - Predicted Crashes by Month', fontsize=14, fontweight='bold')
    axes[ax_i].set_xlabel('Month', fontweight='bold')
    axes[ax_i].set_ylabel('Road', fontweight='bold')
    axes[ax_i].set_xticklabels(months, rotation=0)

plt.suptitle('Peak Crash Months Forecast - Heat Calendar', fontsize=16, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

# Top 10 riskiest combinations
print("\nTOP 10 RISKIEST MONTH-ROAD COMBINATIONS (2025-2026)")
print("-" * 70)
top_risks = predictions_df.nlargest(10, 'predicted_crashes')[['date', 'road', 'predicted_crashes']].copy()
top_risks['month_year'] = top_risks['date'].dt.strftime('%b %Y')
print("\n", top_risks[['month_year', 'road', 'predicted_crashes']].to_string(index=False))

# Actionable insights
print("\n" + "=" * 80)
print("ACTIONABLE INSIGHTS FOR ROAD SAFETY PLANNING")
print("=" * 80)

peak_all = []
for yr in [2025, 2026]:
    pk = predictions_df[predictions_df['year'] == yr].groupby('road').apply(
        lambda x: x.loc[x['predicted_crashes'].idxmax()]
    ).reset_index(drop=True)
    peak_all.append(pk)

peak_combined = pd.concat(peak_all)
peak_month_counts = peak_combined['month'].value_counts()
most_common_peak = peak_month_counts.idxmax()
most_common_peak_name = months[int(most_common_peak) - 1]

print(f"\n1. MOST COMMON PEAK MONTH: {most_common_peak_name}")
print(f"   → {peak_month_counts.max()} out of 14 road-year combinations peak in this month")

max_crashes = predictions_df.groupby('road')['predicted_crashes'].max().sort_values(ascending=False)
print(f"\n2. ROADS REQUIRING MOST ATTENTION:")
for i, (road, crashes) in enumerate(max_crashes.head(3).items(), 1):
    print(f"   {i}. {road:25s} - Peak: {crashes:.0f} crashes/month")

predictions_df['season'] = predictions_df['month'].apply(
    lambda x: 'Q1' if x in [1,2,3] else 'Q2' if x in [4,5,6] else 'Q3' if x in [7,8,9] else 'Q4'
)
seasonal = predictions_df.groupby('season')['predicted_crashes'].sum().sort_values(ascending=False)
print(f"\n3. SEASONAL PATTERNS:")
print(f"   Highest risk quarter: {seasonal.idxmax()} ({seasonal.max():.0f} total crashes)")
print(f"   Lowest risk quarter:  {seasonal.idxmin()} ({seasonal.min():.0f} total crashes)")

print(f"\n4. BEST PREDICTION MODEL PER ROAD:")
for road, model in best_models.items():
    print(f"   {road:25s} → {model}")

print("\n✓ Analysis complete!")
print("=" * 80)
