# -*- coding: utf-8 -*-
"""AADT-Crash Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g9Uj1BpT5DXswof4pXza6u5Ky4LPSeQe

METRO MANILA ROAD CRASH ANALYSIS: Traffic Volume vs Crashes
=============================================================================

Research Question: Does traffic volume increase crashes on major Metro Manila roads?

Dataset:
- Roads: 7 major Metro Manila roads (EDSA, C-5, Commonwealth, Quezon Ave,
         Roxas Blvd, Marcos Highway, Radial Road 10)
- Period: 2019-2024 (72 months)
- Observations: 504 monthly records (7 roads × 6 years × 12 months)
- Source: MMDA MMARAS Annual Reports

Author: Jerdan L. Gondayao, Johnmer M. Tanqui-on
"""

# CELL 1
# Data manipulation
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from pathlib import Path

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.dates as mdates

# Statistical analysis
from scipy import stats
from scipy.stats import pearsonr, spearmanr
import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.tsa.statespace.sarimax import SARIMAX

# Forecasting evaluation
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score


# Warnings
import warnings
warnings.filterwarnings('ignore')

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.float_format', lambda x: '%.2f' % x)

# Plotting style
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

# Set random seed
np.random.seed(42)

# CELL 2
# =============================================================================
# CONFIGURATION & HELPER FUNCTIONS
# =============================================================================

COLORS = {
    'EDSA': '#94A5A6', 'C-5 Road': '#4ECDC4', 'Commonwealth Avenue': '#45B7D1',
    'Quezon Avenue': '#FFA07A', 'Roxas Boulevard': '#98D8C8',
    'Marcos Highway': '#F7DC6F', 'Radial Road 10': '#BB8FCE',
    'primary': '#2C3E50', 'secondary': '#E74C3C'
}

def print_section(title):
    print("\n" + "="*70 + f"\n {title}\n" + "="*70 + "\n")

def get_road_color(road_name):
    return COLORS.get(road_name, '#95A5A6')

def run_sarima_forecast(y, exog=None, forecast_steps=24, title="Forecast", y_label="Value"):
    """Utility function to fit SARIMA and plot results."""
    model = SARIMAX(y, exog=exog, order=(1, 1, 1), seasonal_order=(1, 1, 1, 12),
                    enforce_stationarity=False, enforce_invertibility=False)
    results = model.fit(disp=False)

    last_date = y.index[-1]
    forecast_dates = pd.date_range(start=last_date + pd.DateOffset(months=1), periods=forecast_steps, freq='MS')

    # Use last known exog values for forecast if provided
    exog_forecast = None
    if exog is not None:
        exog_forecast = pd.DataFrame({col: [exog[col].iloc[-1]] * forecast_steps for col in exog.columns}, index=forecast_dates)

    forecast = results.get_forecast(steps=forecast_steps, exog=exog_forecast)
    mean = forecast.predicted_mean
    ci = forecast.conf_int()

    fig, ax = plt.subplots(figsize=(14, 5))
    ax.plot(y.index, y, label='Historical', color='#2E86AB')
    ax.plot(mean.index, mean, label='Forecast', color='#E63946', linestyle='--')
    ax.fill_between(mean.index, ci.iloc[:, 0], ci.iloc[:, 1], color='#E63946', alpha=0.1)
    ax.axvline(x=last_date, color='gray', linestyle=':')
    ax.set_title(title, fontweight='bold')
    ax.set_ylabel(y_label)
    ax.legend()
    plt.show()
    return mean, ci


# CELL 3
# LOAD DATA

print_section("LOADING DATA")

from pathlib import Path

df = pd.read_csv(Path("dataset.csv"))

print("✓ Data loaded successfully!")
print(f"\nDataset shape: {df.shape[0]} rows × {df.shape[1]} columns")

# CELL 4
# INITIAL DATA SUMMARY REPORT

print_section("DATA ACQUISITION SUMMARY REPORT")

print("Dataset Characteristics:")
print(f"  • Total Observations: {len(df):,}")
print(f"  • Time Period: {df['year'].min()}-{df['year'].max()}")
print(f"  • Duration: {df['year'].max() - df['year'].min() + 1} years")
print(f"  • Monthly Data Points: {len(df) / df['road_name'].nunique():.0f} per road")
print(f"  • Roads Covered: {df['road_name'].nunique()}")

print("\n" + "-"*70)
print("Roads in Dataset (sorted by average AADT):")
print("-"*70)

# Create summary by road
road_summary = []
for road in df['road_name'].unique():
    road_data = df[df['road_name'] == road]
    road_summary.append({
        'Road': road,
        'Observations': len(road_data),
        'Avg AADT': road_data['aadt'].mean(),
        'Total Crashes': road_data['crashes_total'].sum(),
        'Fatal': road_data['crashes_fatal'].sum(),
        'Non-Fatal': road_data['crashes_non_fatal'].sum(),
        'Property': road_data['crashes_property'].sum(),
        'Avg Monthly Crashes': road_data['crashes_total'].mean()
    })

road_summary_df = pd.DataFrame(road_summary).sort_values('Avg AADT', ascending=False)

for idx, row in road_summary_df.iterrows():
    print(f"\n{row['Road']}")
    print(f"  • Observations: {int(row['Observations'])}")
    print(f"  • Avg AADT: {row['Avg AADT']:,.0f} vehicles/day")
    print(f"  • Total Crashes (2019-2024): {int(row['Total Crashes']):,}")
    print(f"    - Fatal: {int(row['Fatal'])}")
    print(f"    - Non-Fatal: {int(row['Non-Fatal']):,}")
    print(f"    - Property Damage: {int(row['Property']):,}")
    print(f"  • Avg Monthly Crash Reports: {row['Avg Monthly Crashes']:.1f}")

print("\n" + "-"*70)
print("Overall Statistics:")
print("-"*70)
print(f"  • Total Crashes (all roads, 2019-2024): {df['crashes_total'].sum():,}")
print(f"  • Total Fatal Crashes: {df['crashes_fatal'].sum():,}")
print(f"  • Total Non-Fatal Crashes: {df['crashes_non_fatal'].sum():,}")
print(f"  • Total Property Damage: {df['crashes_property'].sum():,}")
print(f"  • Average Monthly Crashes (per road): {df['crashes_total'].mean():.1f}")
print(f"  • Average AADT (all roads): {df['aadt'].mean():,.0f} vehicles/day")

print("\n" + "-"*70)
print("Crash Severity Breakdown:")
print("-"*70)
total_crashes = df['crashes_total'].sum()
print(f"  • Fatal: {df['crashes_fatal'].sum():,} ({df['crashes_fatal'].sum()/total_crashes*100:.1f}%)")
print(f"  • Non-Fatal Injury: {df['crashes_non_fatal'].sum():,} ({df['crashes_non_fatal'].sum()/total_crashes*100:.1f}%)")
print(f"  • Property Damage Only: {df['crashes_property'].sum():,} ({df['crashes_property'].sum()/total_crashes*100:.1f}%)")


# CELL 5
# AADT TRENDS OVER TIME (2019-2024) - SEPARATE GRAPHS PER ROAD

print_section("TRAFFIC VOLUME ANALYSIS: AADT Trends")

df_yearly = df.groupby(['road_name', 'year'])['aadt'].first().reset_index()

roads_sorted = df.groupby('road_name')['aadt'].mean().sort_values(ascending=False).index

print("AADT by Year for Each Road:")
print("-" * 70)
for road in roads_sorted:
    road_data = df_yearly[df_yearly['road_name'] == road].sort_values('year')
    print(f"\n{road}:")
    for _, row in road_data.iterrows():
        print(f"  {row['year']} - {int(row['aadt']):,}")

print("\n")

fig, axes = plt.subplots(4, 2, figsize=(14, 12))

for idx, road in enumerate(roads_sorted):
    row = idx // 2
    col = idx % 2
    ax = axes[row, col]

    road_data = df_yearly[df_yearly['road_name'] == road].sort_values('year')

    ax.plot(road_data['year'],
            road_data['aadt'],
            color=get_road_color(road),
            linewidth=2.5,
            marker='o',
            markersize=6)

    ax.set_title(f'{road}', fontsize=11, fontweight='bold')
    ax.set_xlabel('Year', fontsize=9)
    ax.set_ylabel('AADT', fontsize=9)
    ax.grid(True, alpha=0.3, linestyle='--')
    ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{int(x):,}'))
    ax.set_xticks(road_data['year'])

axes[3, 1].axis('off')

fig.suptitle('Traffic Volume Trends on Major Metro Manila Roads (2019-2024)',
             fontsize=14, fontweight='bold')

plt.tight_layout()
plt.show()

print("\nAADT Summary Statistics by Road:")
print("-" * 70)
aadt_summary = df.groupby('road_name')['aadt'].agg(['mean', 'min', 'max', 'std'])
aadt_summary.columns = ['Average AADT', 'Min AADT', 'Max AADT', 'Std Dev']
aadt_summary = aadt_summary.sort_values('Average AADT', ascending=False)
print(aadt_summary.to_string())

# CELL 6
# TOTAL CRASH TRENDS OVER TIME (2019-2024) - SEPARATE GRAPHS PER ROAD

print_section("CRASH ANALYSIS: Total Crash Trends")

df_yearly_crashes = df.groupby(['road_name', 'year'])['crashes_total'].sum().reset_index()

roads_sorted = df.groupby('road_name')['crashes_total'].sum().sort_values(ascending=False).index

print("Total Crashes by Year for Each Road:")
print("-" * 70)
for road in roads_sorted:
    road_data = df_yearly_crashes[df_yearly_crashes['road_name'] == road].sort_values('year')
    print(f"\n{road}:")
    for _, row in road_data.iterrows():
        print(f"  {row['year']} - {int(row['crashes_total']):,}")

print("\n")

fig, axes = plt.subplots(4, 2, figsize=(14, 12))

for idx, road in enumerate(roads_sorted):
    row = idx // 2
    col = idx % 2
    ax = axes[row, col]

    road_data = df_yearly_crashes[df_yearly_crashes['road_name'] == road].sort_values('year')

    ax.plot(road_data['year'],
            road_data['crashes_total'],
            color=get_road_color(road),
            linewidth=2.5,
            marker='o',
            markersize=6)

    ax.set_title(f'{road}', fontsize=11, fontweight='bold')
    ax.set_xlabel('Year', fontsize=9)
    ax.set_ylabel('Total Crashes', fontsize=9)
    ax.grid(True, alpha=0.3, linestyle='--')
    ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{int(x):,}'))
    ax.set_xticks(road_data['year'])

axes[3, 1].axis('off')

fig.suptitle('Total Crash Trends on Major Metro Manila Roads (2019-2024)',
             fontsize=14, fontweight='bold')

plt.tight_layout()
plt.show()

print("\nTotal Crashes Summary Statistics by Road:")
print("-" * 70)
crash_summary = df.groupby('road_name')['crashes_total'].agg(['sum', 'mean', 'min', 'max', 'std'])
crash_summary.columns = ['Total Crashes (6 years)', 'Avg Monthly', 'Min Monthly', 'Max Monthly', 'Std Dev']
crash_summary = crash_summary.sort_values('Total Crashes (6 years)', ascending=False)
print(crash_summary.to_string())

# CELL 7
# AADT vs TOTAL CRASHES RELATIONSHIP - SEPARATE GRAPHS PER ROAD

print_section("RELATIONSHIP ANALYSIS: AADT vs Total Crashes")

df_yearly_aadt = df.groupby(['road_name', 'year'])['aadt'].first().reset_index()
df_yearly_crashes = df.groupby(['road_name', 'year'])['crashes_total'].sum().reset_index()

df_yearly_combined = df_yearly_aadt.merge(df_yearly_crashes, on=['road_name', 'year'])

roads_sorted = df.groupby('road_name')['aadt'].mean().sort_values(ascending=False).index

fig, axes = plt.subplots(4, 2, figsize=(16, 14))

for idx, road in enumerate(roads_sorted):
    row = idx // 2
    col = idx % 2
    ax1 = axes[row, col]

    road_data = df_yearly_combined[df_yearly_combined['road_name'] == road].sort_values('year')

    color_aadt = get_road_color(road)
    ax1.plot(road_data['year'],
             road_data['aadt'],
             color=color_aadt,
             linewidth=2.5,
             marker='o',
             markersize=6,
             label='AADT')

    ax1.set_xlabel('Year', fontsize=9, fontweight='bold')
    ax1.set_ylabel('AADT (vehicles/day)', fontsize=9, fontweight='bold', color=color_aadt)
    ax1.tick_params(axis='y', labelcolor=color_aadt)
    ax1.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{int(x):,}'))
    ax1.set_xticks(road_data['year'])
    ax1.grid(True, alpha=0.3, linestyle='--')

    ax2 = ax1.twinx()
    color_crash = '#E74C3C'
    ax2.plot(road_data['year'],
             road_data['crashes_total'],
             color=color_crash,
             linewidth=2.5,
             marker='s',
             markersize=6,
             label='Total Crashes',
             linestyle='--')

    ax2.set_ylabel('Total Crashes', fontsize=9, fontweight='bold', color=color_crash)
    ax2.tick_params(axis='y', labelcolor=color_crash)
    ax2.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{int(x):,}'))

    ax1.set_title(f'{road}', fontsize=11, fontweight='bold')

    lines1, labels1 = ax1.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    ax1.legend(lines1 + lines2, labels1 + labels2, loc='upper left', fontsize=8)

axes[3, 1].axis('off')

fig.suptitle('AADT vs Total Crashes on Major Metro Manila Roads (2019-2024)',
             fontsize=15, fontweight='bold')

plt.tight_layout()
plt.show()

# CELL 8
# STATISTICAL ANALYSIS: AADT vs CRASHES RELATIONSHIP

print_section("RELATIONSHIP ANALYSIS: Does Higher AADT Lead to More Crashes?")

df_yearly_combined = df.groupby(['road_name', 'year']).agg({
    'aadt': 'first',
    'crashes_total': 'sum'
}).reset_index()

print("QUESTION 1: Across different roads, does higher AADT mean more crashes?")
print("-" * 70)

road_comparison = df.groupby('road_name').agg({
    'aadt': 'mean',
    'crashes_total': 'sum'
}).reset_index()
road_comparison.columns = ['Road', 'Avg AADT', 'Total Crashes (6 years)']
road_comparison = road_comparison.sort_values('Avg AADT', ascending=False)

print("\nRoad Rankings by Traffic Volume and Crashes:")
for idx, row in road_comparison.iterrows():
    print(f"{row['Road']:25} | Avg AADT: {int(row['Avg AADT']):>10,} | Total Crashes: {int(row['Total Crashes (6 years)']):>7,}")

# Calculate correlation across roads
corr_across_roads = road_comparison['Avg AADT'].corr(road_comparison['Total Crashes (6 years)'])
print(f"\nCorrelation between AADT and Total Crashes (across roads): {corr_across_roads:.3f}")

if corr_across_roads > 0.7:
    print("✓ STRONG POSITIVE correlation - Roads with higher traffic volume have significantly more crashes")
elif corr_across_roads > 0.4:
    print("✓ MODERATE POSITIVE correlation - Roads with higher traffic tend to have more crashes")
elif corr_across_roads > 0:
    print("✓ WEAK POSITIVE correlation - Higher traffic shows some association with more crashes")
else:
    print("✗ NO or NEGATIVE correlation - Higher traffic does not necessarily mean more crashes")

print("\n" + "=" * 70)
print("\nQUESTION 2: As AADT increases over time, do crashes also increase?")
print("-" * 70)

# Analyze time trends for each road
print("\nYear-over-Year Correlation Analysis (per road):")
print("-" * 70)

correlation_results = []
for road in df_yearly_combined['road_name'].unique():
    road_data = df_yearly_combined[df_yearly_combined['road_name'] == road].sort_values('year')

    corr = road_data['aadt'].corr(road_data['crashes_total'])
    correlation_results.append({'Road': road, 'Correlation': corr})

    aadt_2019 = road_data[road_data['year'] == 2019]['aadt'].values[0]
    aadt_2024 = road_data[road_data['year'] == 2024]['aadt'].values[0]
    crashes_2019 = road_data[road_data['year'] == 2019]['crashes_total'].values[0]
    crashes_2024 = road_data[road_data['year'] == 2024]['crashes_total'].values[0]

    aadt_change = ((aadt_2024 - aadt_2019) / aadt_2019) * 100
    crash_change = ((crashes_2024 - crashes_2019) / crashes_2019) * 100

    print(f"\n{road}:")
    print(f"  Correlation coefficient: {corr:.3f}")
    print(f"  AADT change (2019→2024): {aadt_change:+.1f}%")
    print(f"  Crash change (2019→2024): {crash_change:+.1f}%")

    if corr > 0.5:
        print(f"  → Strong positive relationship - crashes tend to increase with AADT")
    elif corr > 0:
        print(f"  → Weak positive relationship - some alignment between AADT and crashes")
    elif corr > -0.5:
        print(f"  → Weak negative relationship - crashes decrease as AADT increases")
    else:
        print(f"  → Strong negative relationship - higher AADT associated with fewer crashes")

overall_corr = df_yearly_combined['aadt'].corr(df_yearly_combined['crashes_total'])
print("\n" + "=" * 70)
print(f"\nOVERALL CORRELATION (all roads, all years): {overall_corr:.3f}")

corr_df = pd.DataFrame(correlation_results)
avg_corr = corr_df['Correlation'].mean()
print(f"AVERAGE CORRELATION (across roads): {avg_corr:.3f}")

print("\n" + "=" * 70)
print("KEY FINDINGS:")
print("=" * 70)

if corr_across_roads > 0.5:
    print("\n1. ACROSS ROADS: YES - Higher traffic volume is associated with MORE crashes")
    print("   Roads with more vehicles tend to experience more crash incidents.")
else:
    print("\n1. ACROSS ROADS: WEAK/NO - Higher traffic volume doesn't strongly predict crashes")
    print("   Other factors besides traffic volume influence crash rates.")

if avg_corr > 0.3:
    print("\n2. OVER TIME: YES - As AADT increases, crashes tend to increase")
    print("   When traffic volume grows on a road, crash incidents typically rise.")
elif avg_corr > -0.3:
    print("\n2. OVER TIME: MIXED - Relationship varies by road")
    print("   Some roads show increases in crashes with higher traffic, others don't.")
else:
    print("\n2. OVER TIME: NO - As AADT increases, crashes tend to DECREASE")
    print("   Higher traffic volumes are associated with fewer crashes (possibly due to")
    print("   slower speeds or improved infrastructure).")


print("\n" + "=" * 70)

# CELL 9
# QUICK CRASH RATE TEST
print("=" * 80)
print("QUICK TEST: How does normalization change the rankings?")
print("=" * 80)

road_comparison = df.groupby('road_name').agg({
    'aadt': 'mean',
    'crashes_total': 'sum'
}).reset_index()

road_comparison['crash_rate_per_100k'] = (
    road_comparison['crashes_total'] / road_comparison['aadt']
) * 100000

print("\nRanking by TOTAL CRASHES:")
print(road_comparison.sort_values('crashes_total', ascending=False)[['road_name', 'crashes_total']])

print("\nRanking by CRASH RATE (per 100k AADT):")
print(road_comparison.sort_values('crash_rate_per_100k', ascending=False)[['road_name', 'crash_rate_per_100k']])

# CELL 10
# CRASH SEVERITY TRENDS OVER TIME (2019-2024) - SEPARATE GRAPHS PER ROAD

print_section("CRASH SEVERITY ANALYSIS: Fatal, Non-Fatal, and Property Damage Trends")

df_yearly_severity = df.groupby(['road_name', 'year']).agg({
    'crashes_fatal': 'sum',
    'crashes_non_fatal': 'sum',
    'crashes_property': 'sum'
}).reset_index()

roads_sorted = df.groupby('road_name')['crashes_total'].sum().sort_values(ascending=False).index

print("Crash Severity by Year for Each Road:")
print("-" * 70)
for road in roads_sorted:
    road_data = df_yearly_severity[df_yearly_severity['road_name'] == road].sort_values('year')
    print(f"\n{road}:")
    for _, row in road_data.iterrows():
        print(f"  {row['year']} - Fatal: {int(row['crashes_fatal']):>3} | Non-Fatal: {int(row['crashes_non_fatal']):>5,} | Property: {int(row['crashes_property']):>5,}")

print("\n")

fig, axes = plt.subplots(4, 2, figsize=(16, 14))

for idx, road in enumerate(roads_sorted):
    row = idx // 2
    col = idx % 2
    ax = axes[row, col]

    road_data = df_yearly_severity[df_yearly_severity['road_name'] == road].sort_values('year')

    ax.plot(road_data['year'],
            road_data['crashes_fatal'],
            color='#E74C3C',
            linewidth=2.5,
            marker='o',
            markersize=6,
            label='Fatal')

    ax.plot(road_data['year'],
            road_data['crashes_non_fatal'],
            color='#F39C12',
            linewidth=2.5,
            marker='s',
            markersize=6,
            label='Non-Fatal Injury')

    ax.plot(road_data['year'],
            road_data['crashes_property'],
            color='#3498DB',
            linewidth=2.5,
            marker='^',
            markersize=6,
            label='Property Damage')

    ax.set_title(f'{road}', fontsize=11, fontweight='bold')
    ax.set_xlabel('Year', fontsize=9)
    ax.set_ylabel('Number of Crashes', fontsize=9)
    ax.grid(True, alpha=0.3, linestyle='--')
    ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{int(x):,}'))
    ax.set_xticks(road_data['year'])
    ax.legend(loc='best', fontsize=8)

axes[3, 1].axis('off')

fig.suptitle('Crash Severity Trends on Major Metro Manila Roads (2019-2024)',
             fontsize=15, fontweight='bold')

plt.tight_layout()
plt.show()

print("\nCrash Severity Summary Statistics by Road (2019-2024):")
print("-" * 70)
severity_summary = df.groupby('road_name').agg({
    'crashes_fatal': 'sum',
    'crashes_non_fatal': 'sum',
    'crashes_property': 'sum',
    'crashes_total': 'sum'
}).reset_index()

severity_summary['Fatal %'] = (severity_summary['crashes_fatal'] / severity_summary['crashes_total'] * 100)
severity_summary['Non-Fatal %'] = (severity_summary['crashes_non_fatal'] / severity_summary['crashes_total'] * 100)
severity_summary['Property %'] = (severity_summary['crashes_property'] / severity_summary['crashes_total'] * 100)

severity_summary = severity_summary.sort_values('crashes_total', ascending=False)
severity_summary.columns = ['Road', 'Fatal', 'Non-Fatal', 'Property', 'Total', 'Fatal %', 'Non-Fatal %', 'Property %']

print(severity_summary.to_string(index=False))

# CELL 11
# AVERAGE CRASHES PER MONTH (JANUARY - DECEMBER) PER ROAD

print_section("AVERAGE CRASHES PER MONTH PER ROAD")

month_names = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
               'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

roads_sorted = df.groupby('road_name')['crashes_total'].sum().sort_values(ascending=False).index

print("Average Crashes per Month by Road (2019-2024):")
print("-" * 70)
for road in roads_sorted:
    road_data = df[df['road_name'] == road].groupby('month')['crashes_total'].mean().reset_index()
    print(f"\n{road}:")
    for _, row in road_data.iterrows():
        print(f"  {month_names[int(row['month'])-1]:10} - {row['crashes_total']:.1f} crashes")

print("\n")

fig, axes = plt.subplots(4, 2, figsize=(16, 14))

for idx, road in enumerate(roads_sorted):
    row = idx // 2
    col = idx % 2
    ax = axes[row, col]

    road_data = df[df['road_name'] == road].groupby('month')['crashes_total'].mean().reset_index()
    road_data = road_data.sort_values('month')

    bars = ax.bar(range(12),
                  road_data['crashes_total'],
                  color=get_road_color(road),
                  edgecolor='black',
                  linewidth=1.2)

    for i, (bar, value) in enumerate(zip(bars, road_data['crashes_total'])):
        ax.text(bar.get_x() + bar.get_width()/2,
                bar.get_height() + max(road_data['crashes_total']) * 0.02,
                f'{value:.0f}',
                ha='center',
                va='bottom',
                fontweight='bold',
                fontsize=8)

    ax.set_title(f'{road}', fontsize=11, fontweight='bold')
    ax.set_xlabel('Month', fontsize=9)
    ax.set_ylabel('Avg Crashes', fontsize=9)
    ax.set_xticks(range(12))
    ax.set_xticklabels(month_names, rotation=45, ha='right', fontsize=8)
    ax.grid(axis='y', alpha=0.3, linestyle='--')

axes[3, 1].axis('off')

fig.suptitle('Average Monthly Crash Patterns by Road (2019-2024)',
             fontsize=15, fontweight='bold')

plt.tight_layout()
plt.show()

# CELL 12
# MOST DANGEROUS ROAD PER MONTH ANALYSIS - HEATMAP

print_section("MOST DANGEROUS ROAD PER MONTH")

month_names = ['January', 'February', 'March', 'April', 'May', 'June',
               'July', 'August', 'September', 'October', 'November', 'December']
month_names_short = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                     'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

monthly_road_crashes = df.groupby(['month', 'road_name'])['crashes_total'].mean().reset_index()


fig, ax = plt.subplots(figsize=(14, 6))

pivot_data = monthly_road_crashes.pivot(index='road_name', columns='month', values='crashes_total')
pivot_data.columns = month_names_short

pivot_data['Total'] = pivot_data.sum(axis=1)
pivot_data = pivot_data.sort_values('Total', ascending=False).drop('Total', axis=1)

im = ax.imshow(pivot_data.values, cmap='YlOrRd', aspect='auto')

ax.set_xticks(range(12))
ax.set_xticklabels(month_names_short)
ax.set_yticks(range(len(pivot_data)))
ax.set_yticklabels(pivot_data.index)

for i in range(len(pivot_data)):
    for j in range(12):
        text = ax.text(j, i, f'{pivot_data.values[i, j]:.0f}',
                       ha="center", va="center", color="black", fontsize=8, fontweight='bold')

ax.set_title('Crash Heatmap: All Roads Across All Months (2019-2024)', fontsize=14, fontweight='bold', pad=15)
ax.set_xlabel('Month', fontsize=12, fontweight='bold')
ax.set_ylabel('Road', fontsize=12, fontweight='bold')

cbar = plt.colorbar(im, ax=ax)
cbar.set_label('Average Crashes', rotation=270, labelpad=20, fontweight='bold')

plt.tight_layout()
plt.show()

# CELL 13
# =============================================================================
# FEATURE ENGINEERING & FORECAST SETUP
# =============================================================================

print_section("FEATURE ENGINEERING & FORECAST CONFIGURATION")

FORECAST_MONTHS = 24
last_date = pd.to_datetime(f"{df['year'].max()}-{df['month'].max():02d}-01")
forecast_dates = pd.date_range(start=last_date + pd.DateOffset(months=1),
                               periods=FORECAST_MONTHS, freq='MS')

df_ml = df.copy()
df_ml['date'] = pd.to_datetime(df_ml[['year', 'month']].assign(day=1))
df_ml = df_ml.sort_values(['road_name', 'date']).reset_index(drop=True)

# Cyclical month features
df_ml['month_sin'] = np.sin(2 * np.pi * df_ml['month'] / 12)
df_ml['month_cos'] = np.cos(2 * np.pi * df_ml['month'] / 12)

# Crash rates (normalized by traffic volume)
df_ml['crash_rate_per_100k'] = (df_ml['crashes_total'] / df_ml['aadt']) * 100000
df_ml['is_pandemic'] = df_ml['year'].isin([2020, 2021]).astype(int)

print("✓ Features engineered:")
print("  • Cyclical encoding: month_sin, month_cos")
print("  • Crash rate per 100k AADT (traffic-normalized)")
print("  • Pandemic flag (2020-2021)")
print(f"\n  Forecast horizon: {FORECAST_MONTHS} months ({forecast_dates[0].strftime('%b %Y')} – {forecast_dates[-1].strftime('%b %Y')})")
print(f"  Model: SARIMAX(1,1,1)(1,1,1,12) with AADT as exogenous variable")

# CELL 14
# =============================================================================
# SARIMA FORECASTING: PER-ROAD CRASH PREDICTIONS (2025-2026)
# =============================================================================

print_section("SARIMA FORECASTING: Per-Road Crash Predictions (2025-2026)")

predictions_by_road = {}
sarima_eval = {}

roads_sorted = sorted(df_ml['road_name'].unique())

for road in roads_sorted:
    road_data = df_ml[df_ml['road_name'] == road].set_index('date').sort_index()
    y = road_data['crashes_total']
    exog = road_data[['aadt']]

    print(f"Forecasting {road}...")
    mean_fc, ci_fc = run_sarima_forecast(
        y, exog=exog,
        title=f"{road} – Crash Forecast (2025-2026)",
        y_label="Total Crashes"
    )
    predictions_by_road[road] = {
        'forecast': mean_fc,
        'lower_ci': ci_fc.iloc[:, 0],
        'upper_ci': ci_fc.iloc[:, 1],
        'historical': y
    }

    # Evaluate on 2024 holdout
    train = road_data[road_data.index < '2024-01-01']
    test = road_data[road_data.index >= '2024-01-01']
    if len(train) > 0 and len(test) > 0:
        try:
            m = SARIMAX(train['crashes_total'], exog=train[['aadt']],
                        order=(1, 1, 1), seasonal_order=(1, 1, 1, 12),
                        enforce_stationarity=False, enforce_invertibility=False)
            res = m.fit(disp=False)
            pred = res.get_forecast(steps=len(test), exog=test[['aadt']]).predicted_mean
            sarima_eval[road] = {
                'MAE': mean_absolute_error(test['crashes_total'], pred),
                'RMSE': np.sqrt(mean_squared_error(test['crashes_total'], pred)),
                'R2': r2_score(test['crashes_total'], pred)
            }
        except:
            pass

# Per-road forecast summary
print("\n" + "=" * 80)
print("PER-ROAD FORECAST SUMMARY")
print("=" * 80)

for road in roads_sorted:
    data = predictions_by_road[road]
    hist_avg = data['historical'][-12:].mean()
    fc_avg = data['forecast'].mean()
    change = ((fc_avg - hist_avg) / hist_avg) * 100

    print(f"\n  {road}:")
    print(f"    2024 Avg: {hist_avg:.0f} crashes/month")
    print(f"    Forecast Avg: {fc_avg:.0f} crashes/month ({change:+.1f}%)")
    print(f"    2025 Total: {data['forecast'][:12].sum():.0f} | 2026 Total: {data['forecast'][12:].sum():.0f}")

    if road in sarima_eval:
        e = sarima_eval[road]
        print(f"    Model Accuracy (2024 test): MAE={e['MAE']:.1f}, RMSE={e['RMSE']:.1f}, R²={e['R2']:.3f}")

# CELL 15
# =============================================================================
# SARIMA FORECASTING: ALL ROADS COMBINED (2025-2026)
# =============================================================================

print_section("SARIMA FORECASTING: All Roads Combined (2025-2026)")

total_crashes = df_ml.groupby('date')['crashes_total'].sum().sort_index()
total_aadt = df_ml.groupby('date')['aadt'].sum().sort_index()

print(f"Dataset: {len(total_crashes)} months of combined crash data")
print(f"Period: {total_crashes.index[0].strftime('%Y-%m')} to {total_crashes.index[-1].strftime('%Y-%m')}")
print(f"Total crashes across all roads: {total_crashes.sum():,}")
print("\n" + "=" * 70)

exog_total = pd.DataFrame({'aadt': total_aadt})

print("Building SARIMAX model for combined Metro Manila data...")
model_total = SARIMAX(
    total_crashes, exog=exog_total,
    order=(1, 1, 1), seasonal_order=(1, 1, 1, 12),
    enforce_stationarity=False, enforce_invertibility=False
)
results_total = model_total.fit(disp=False, maxiter=200)
print(f"✓ Model fitted – AIC: {results_total.aic:.2f}")

exog_forecast_total = pd.DataFrame({
    'aadt': [total_aadt.iloc[-1]] * FORECAST_MONTHS
}, index=forecast_dates)

forecast_total = results_total.get_forecast(steps=FORECAST_MONTHS, exog=exog_forecast_total)
forecast_mean_total = forecast_total.predicted_mean
forecast_ci_total = forecast_total.conf_int(alpha=0.05)

fig, ax = plt.subplots(figsize=(16, 7))

ax.plot(total_crashes.index, total_crashes.values,
        color='#2E86AB', linewidth=2.5, marker='o', markersize=4,
        label='Historical Total Crashes', zorder=3)
ax.plot(forecast_mean_total.index, forecast_mean_total.values,
        color='#E63946', linewidth=2.5, linestyle='--', marker='o', markersize=4,
        label='Forecast Total Crashes', zorder=3)
ax.fill_between(forecast_mean_total.index,
                forecast_ci_total.iloc[:, 0], forecast_ci_total.iloc[:, 1],
                color='#E63946', alpha=0.15, label='95% Confidence Interval')
ax.axvline(x=pd.Timestamp('2024-12-01'), color='gray',
           linestyle=':', linewidth=2, alpha=0.7, label='Forecast Start')

ax.set_title('Metro Manila Total Crashes – All Roads Combined (SARIMA Forecast)',
             fontsize=16, fontweight='bold', pad=20)
ax.set_xlabel('Date', fontsize=12, fontweight='bold')
ax.set_ylabel('Total Crashes (All Roads)', fontsize=12, fontweight='bold')
ax.legend(loc='lower left', fontsize=11, framealpha=0.9)
ax.grid(True, alpha=0.3, linestyle='--')
ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
ax.xaxis.set_major_locator(mdates.YearLocator())

avg_2024_all = total_crashes[-12:].mean()
avg_fc_all = forecast_mean_total.mean()
change_all = ((avg_fc_all - avg_2024_all) / avg_2024_all) * 100

textstr = f'2024 Avg: {avg_2024_all:.0f} crashes/month\n'
textstr += f'Forecast Avg: {avg_fc_all:.0f} crashes/month\n'
textstr += f'Expected Change: {change_all:+.1f}%\n\n'
textstr += f'2025 Total: {forecast_mean_total[:12].sum():.0f} crashes\n'
textstr += f'2026 Total: {forecast_mean_total[12:].sum():.0f} crashes'

props = dict(boxstyle='round', facecolor='lightblue', alpha=0.8)
ax.text(0.02, 0.98, textstr, transform=ax.transAxes, fontsize=11,
        verticalalignment='top', bbox=props)
plt.tight_layout()
plt.show()

print("\n" + "=" * 70)
print("METRO MANILA TOTAL CRASH FORECAST SUMMARY")
print("=" * 70)
print(f"\n  2024 Actual Total: {total_crashes[-12:].sum():.0f} crashes")
print(f"  2025 Forecast:     {forecast_mean_total[:12].sum():.0f} crashes ({change_all:+.1f}% vs 2024)")
print(f"  2026 Forecast:     {forecast_mean_total[12:].sum():.0f} crashes")
print(f"\n  Average monthly crashes (forecast): {avg_fc_all:.0f}")
print(f"\n  95% Confidence Interval:")
print(f"    Lower bound: {forecast_ci_total.iloc[:, 0].mean():.0f} crashes/month")
print(f"    Upper bound: {forecast_ci_total.iloc[:, 1].mean():.0f} crashes/month")

# CELL 16
# =============================================================================
# SARIMA FORECASTING: CRASH SEVERITY TYPES (2025-2026)
# =============================================================================

print_section("SARIMA FORECASTING: Crash Types – Fatal, Non-Fatal, Property (2025-2026)")

crash_types = df_ml.groupby('date').agg({
    'crashes_fatal': 'sum', 'crashes_non_fatal': 'sum',
    'crashes_property': 'sum', 'aadt': 'sum'
}).sort_index()

crash_type_predictions = {}
labels = {
    'crashes_fatal': 'Fatal Crashes',
    'crashes_non_fatal': 'Non-Fatal Injury Crashes',
    'crashes_property': 'Property Damage Only'
}

for crash_type in ['crashes_fatal', 'crashes_non_fatal', 'crashes_property']:
    print(f"\nForecasting: {labels[crash_type]}")
    y = crash_types[crash_type]
    exog = pd.DataFrame({'aadt': crash_types['aadt']})

    model_type = SARIMAX(y, exog=exog, order=(1, 1, 1), seasonal_order=(1, 1, 1, 12),
                         enforce_stationarity=False, enforce_invertibility=False)
    results_type = model_type.fit(disp=False, maxiter=200)

    exog_fc = pd.DataFrame({'aadt': [crash_types['aadt'].iloc[-1]] * FORECAST_MONTHS}, index=forecast_dates)
    forecast_type = results_type.get_forecast(steps=FORECAST_MONTHS, exog=exog_fc)

    crash_type_predictions[crash_type] = {
        'historical': y,
        'forecast': forecast_type.predicted_mean,
        'lower_ci': forecast_type.conf_int(alpha=0.05).iloc[:, 0],
        'upper_ci': forecast_type.conf_int(alpha=0.05).iloc[:, 1]
    }
    print(f"  ✓ AIC: {results_type.aic:.2f}")
    print(f"  ✓ 2025: {forecast_type.predicted_mean[:12].sum():.0f} | 2026: {forecast_type.predicted_mean[12:].sum():.0f}")

fig, ax = plt.subplots(figsize=(16, 8))
colors_sev = {'crashes_fatal': '#DC2F02', 'crashes_non_fatal': '#F77F00', 'crashes_property': '#06A77D'}

for ct, data in crash_type_predictions.items():
    c = colors_sev[ct]
    lbl = labels[ct]
    ax.plot(data['historical'].index, data['historical'].values,
            color=c, linewidth=2, marker='o', markersize=3, label=f'{lbl} (Historical)', alpha=0.8)
    ax.plot(data['forecast'].index, data['forecast'].values,
            color=c, linewidth=2, marker='o', markersize=3, label=f'{lbl} (Forecast)', linestyle='--', alpha=0.8)
    ax.fill_between(data['forecast'].index, data['lower_ci'], data['upper_ci'], color=c, alpha=0.08)

ax.axvline(x=pd.Timestamp('2024-12-01'), color='gray', linestyle=':', linewidth=2, alpha=0.7, label='Forecast Start')
ax.set_title('Metro Manila Crash Type Forecast by Severity (SARIMA)', fontsize=16, fontweight='bold', pad=20)
ax.set_xlabel('Date', fontsize=12, fontweight='bold')
ax.set_ylabel('Number of Crashes', fontsize=12, fontweight='bold')
ax.legend(loc='upper left', fontsize=9, framealpha=0.9, ncol=2)
ax.grid(True, alpha=0.3, linestyle='--')
ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
ax.xaxis.set_major_locator(mdates.YearLocator())
plt.tight_layout()
plt.show()

print("\n" + "=" * 70)
print("CRASH TYPE FORECAST SUMMARY (2025-2026)")
print("=" * 70)

summary_data = []
for ct, data in crash_type_predictions.items():
    h24 = data['historical'][-12:].sum()
    f25 = data['forecast'][:12].sum()
    f26 = data['forecast'][12:].sum()
    chg = ((f25 - h24) / h24) * 100
    summary_data.append({
        'Crash Type': labels[ct], '2024 Actual': int(h24),
        '2025 Forecast': int(f25), '2026 Forecast': int(f26), 'Change %': f'{chg:+.1f}%'
    })

print("\n", pd.DataFrame(summary_data).to_string(index=False))

total_fc = sum([d['forecast'].sum() for d in crash_type_predictions.values()])
print(f"\nExpected Severity Distribution (2025-2026):")
for ct, data in crash_type_predictions.items():
    pct = (data['forecast'].sum() / total_fc) * 100
    print(f"  {labels[ct]:30s}: {pct:5.1f}%")

# CELL 17
# =============================================================================
# SARIMA: CRASH RATE PER 100K AADT (Safety Trends)
# =============================================================================

print_section("SARIMA FORECASTING: Crash Rate per 100k AADT (Safety Trends)")

print("Why Crash Rate Matters:")
print("  → Shows if roads are getting safer/more dangerous independent of traffic growth")
print("  → Helps identify if safety improvements are working")
print("  → Fair comparison across roads with different traffic volumes")
print("\n" + "=" * 80)

crash_rate_predictions = {}

for i, road in enumerate(roads_sorted, 1):
    print(f"\n[{i}/7] {road}")
    print("-" * 60)

    road_data = df_ml[df_ml['road_name'] == road].sort_values('date').set_index('date')
    y_rate = road_data['crash_rate_per_100k']

    try:
        model_rate = SARIMAX(y_rate, order=(1, 1, 1), seasonal_order=(1, 1, 1, 12),
                             enforce_stationarity=False, enforce_invertibility=False)
        results_rate = model_rate.fit(disp=False, maxiter=200)

        fc_rate = results_rate.get_forecast(steps=FORECAST_MONTHS)
        fc_mean_rate = fc_rate.predicted_mean
        fc_ci_rate = fc_rate.conf_int(alpha=0.05)

        crash_rate_predictions[road] = {
            'historical': y_rate, 'forecast': fc_mean_rate,
            'lower_ci': fc_ci_rate.iloc[:, 0], 'upper_ci': fc_ci_rate.iloc[:, 1]
        }

        avg24 = y_rate[-12:].mean()
        avg_fc = fc_mean_rate.mean()
        chg = ((avg_fc - avg24) / avg24) * 100

        fig, ax = plt.subplots(figsize=(14, 5))
        ax.plot(y_rate.index, y_rate.values, color='#06A77D', linewidth=2, marker='o', markersize=3, label='Historical')
        ax.plot(fc_mean_rate.index, fc_mean_rate.values, color='#DC2F02', linewidth=2, linestyle='--', marker='o', markersize=3, label='Forecast')
        ax.fill_between(fc_mean_rate.index, fc_ci_rate.iloc[:, 0], fc_ci_rate.iloc[:, 1], color='#DC2F02', alpha=0.15)
        ax.axvline(x=pd.Timestamp('2024-12-01'), color='gray', linestyle=':', linewidth=2, alpha=0.7)
        ax.set_title(f'{road} – Crash Rate Forecast (per 100k AADT)', fontsize=14, fontweight='bold')
        ax.set_ylabel('Crash Rate (per 100k AADT)')
        ax.legend(fontsize=10)
        ax.grid(True, alpha=0.3, linestyle='--')
        ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))

        box_color = 'lightgreen' if chg < 0 else 'lightyellow'
        trend_txt = '✓ Improving Safety' if chg < 0 else '⚠ Worsening Safety'
        txt = f'2024 Rate: {avg24:.1f}\nForecast: {avg_fc:.1f}\nTrend: {chg:+.1f}%\n{trend_txt}'
        ax.text(0.02, 0.98, txt, transform=ax.transAxes, fontsize=10,
                verticalalignment='top', bbox=dict(boxstyle='round', facecolor=box_color, alpha=0.8))
        plt.tight_layout()
        plt.show()

        print(f"  Safety Trend: {chg:+.1f}% ({'Improving' if chg < 0 else 'Worsening'})")

    except Exception as e:
        print(f"  ✗ Error: {str(e)}")

print("\n" + "=" * 80)
print("CRASH RATE FORECAST SUMMARY (Safety Trends)")
print("=" * 80)

safety_rows = []
for road, data in crash_rate_predictions.items():
    a24 = data['historical'][-12:].mean()
    afc = data['forecast'].mean()
    chg = ((afc - a24) / a24) * 100
    safety_rows.append({
        'Road': road, '2024 Rate': f'{a24:.1f}', 'Forecast Rate': f'{afc:.1f}',
        'Change %': f'{chg:+.1f}%', 'Trend': '✓ Improving' if chg < 0 else '⚠ Worsening'
    })

print("\n", pd.DataFrame(safety_rows).to_string(index=False))

# CELL 18
# =============================================================================
# MODEL EVALUATION: SARIMA Performance Summary
# =============================================================================

print_section("SARIMA MODEL EVALUATION (2024 Holdout Test)")

print("Evaluation method: Train on 2019-2023, test on 2024 (12-month holdout)")
print("=" * 80)

eval_rows = []
for road in roads_sorted:
    if road in sarima_eval:
        e = sarima_eval[road]
        eval_rows.append({'Road': road, 'MAE': e['MAE'], 'RMSE': e['RMSE'], 'R²': e['R2']})

eval_df = pd.DataFrame(eval_rows)
print("\n", eval_df.to_string(index=False, float_format='%.2f'))

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

for ax_i, (metric, color) in enumerate([('MAE', '#2E86AB'), ('RMSE', '#E63946'), ('R²', '#06A77D')]):
    ax = axes[ax_i]
    vals = eval_df[metric].values
    roads_short = [r[:12] + '..' if len(r) > 12 else r for r in eval_df['Road']]
    bars = ax.barh(roads_short, vals, color=color, edgecolor='black', linewidth=0.5)
    ax.set_title(f'{metric}', fontsize=14, fontweight='bold')
    ax.grid(axis='x', alpha=0.3, linestyle='--')
    for bar, val in zip(bars, vals):
        ax.text(bar.get_width() + max(vals) * 0.02, bar.get_y() + bar.get_height()/2,
                f'{val:.2f}', va='center', fontsize=9, fontweight='bold')

fig.suptitle('SARIMA Model Performance by Road (2024 Holdout)', fontsize=16, fontweight='bold')
plt.tight_layout()
plt.show()

avg_mae = eval_df['MAE'].mean()
avg_r2 = eval_df['R²'].mean()
print(f"\nOverall SARIMA Performance:")
print(f"  Average MAE: {avg_mae:.1f} crashes/month")
print(f"  Average R²:  {avg_r2:.3f}")

if avg_r2 > 0.5:
    print("  → Good predictive performance – model captures crash patterns well")
elif avg_r2 > 0:
    print("  → Moderate performance – model captures some patterns but has room for improvement")
else:
    print("  → Weak performance – crash patterns are difficult to predict with available features")

# CELL 18
# =============================================================================
# PEAK CRASH MONTHS & ACTIONABLE INSIGHTS (2025-2026)
# =============================================================================

print_section("PEAK CRASH MONTHS & ACTIONABLE INSIGHTS (2025-2026)")

all_predictions = []
for road, data in predictions_by_road.items():
    fd = pd.DataFrame({
        'date': data['forecast'].index, 'road': road,
        'predicted_crashes': data['forecast'].values,
        'lower_ci': data['lower_ci'].values, 'upper_ci': data['upper_ci'].values
    })
    fd['year'] = fd['date'].dt.year
    fd['month'] = fd['date'].dt.month
    all_predictions.append(fd)

predictions_df = pd.concat(all_predictions, ignore_index=True)
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

for yr in [2025, 2026]:
    print(f"\nPEAK CRASH MONTHS BY ROAD ({yr})")
    print("-" * 70)
    peak = predictions_df[predictions_df['year'] == yr].groupby('road').apply(
        lambda x: x.loc[x['predicted_crashes'].idxmax()]
    ).reset_index(drop=True)
    for _, row in peak.iterrows():
        print(f"  {row['road']:25s} → {months[int(row['month'])-1]} {yr} ({row['predicted_crashes']:.0f} crashes)")

print("\nOVERALL MONTHLY RISK RANKINGS (2025-2026 Combined)")
print("-" * 70)

monthly_totals = predictions_df.groupby('month')['predicted_crashes'].sum().sort_values(ascending=False)
for mnum, total in monthly_totals.items():
    avg = total / 2 / 7
    print(f"  {months[int(mnum)-1]:3s}: {avg:.0f} avg crashes/road/month (Total all roads: {total:.0f})")

fig, axes = plt.subplots(1, 2, figsize=(18, 6))

for ax_i, yr in enumerate([2025, 2026]):
    hm = predictions_df[predictions_df['year'] == yr].pivot_table(
        index='road', columns='month', values='predicted_crashes', aggfunc='sum')
    sns.heatmap(hm, annot=True, fmt='.0f', cmap='YlOrRd',
                cbar_kws={'label': 'Predicted Crashes'}, ax=axes[ax_i])
    axes[ax_i].set_title(f'{yr} – Predicted Crashes by Road × Month', fontsize=14, fontweight='bold')
    axes[ax_i].set_xlabel('Month', fontweight='bold')
    axes[ax_i].set_ylabel('Road', fontweight='bold')
    axes[ax_i].set_xticklabels(months, rotation=0)

plt.suptitle('Crash Forecast Heat Calendar (2025-2026)', fontsize=16, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

print("\nTOP 10 RISKIEST MONTH-ROAD COMBINATIONS (2025-2026)")
print("-" * 70)
top10 = predictions_df.nlargest(10, 'predicted_crashes')[['date', 'road', 'predicted_crashes']].copy()
top10['month_year'] = top10['date'].dt.strftime('%b %Y')
print("\n", top10[['month_year', 'road', 'predicted_crashes']].to_string(index=False))

print("\n" + "=" * 80)
print("ACTIONABLE INSIGHTS FOR ROAD SAFETY PLANNING")
print("=" * 80)

peak_all = []
for yr in [2025, 2026]:
    pk = predictions_df[predictions_df['year'] == yr].groupby('road').apply(
        lambda x: x.loc[x['predicted_crashes'].idxmax()]).reset_index(drop=True)
    peak_all.append(pk)
peak_combined = pd.concat(peak_all)
peak_counts = peak_combined['month'].value_counts()
top_peak = months[int(peak_counts.idxmax()) - 1]

print(f"\n1. MOST COMMON PEAK MONTH: {top_peak}")
print(f"   → {peak_counts.max()} of 14 road-year combinations peak in {top_peak}")
print(f"   → Recommendation: Intensify enforcement and monitoring during {top_peak}")

max_cr = predictions_df.groupby('road')['predicted_crashes'].max().sort_values(ascending=False)
print(f"\n2. ROADS REQUIRING MOST ATTENTION:")
for i, (road, cr) in enumerate(max_cr.head(3).items(), 1):
    print(f"   {i}. {road:25s} – Peak month: {cr:.0f} crashes")

predictions_df['season'] = predictions_df['month'].apply(
    lambda x: 'Q1 (Jan-Mar)' if x in [1,2,3] else 'Q2 (Apr-Jun)' if x in [4,5,6]
    else 'Q3 (Jul-Sep)' if x in [7,8,9] else 'Q4 (Oct-Dec)')
seasonal = predictions_df.groupby('season')['predicted_crashes'].sum().sort_values(ascending=False)
print(f"\n3. SEASONAL RISK PATTERNS:")
for szn, total in seasonal.items():
    avg = total / 2 / 7
    print(f"   {szn:20s}: {avg:.0f} avg crashes/road/month (Total: {total:.0f})")

print(f"\n4. YEAR-OVER-YEAR FORECAST:")
total_2025 = predictions_df[predictions_df['year'] == 2025]['predicted_crashes'].sum()
total_2026 = predictions_df[predictions_df['year'] == 2026]['predicted_crashes'].sum()
yoy_chg = ((total_2026 - total_2025) / total_2025) * 100
print(f"   2025 Total (all roads): {total_2025:.0f} crashes")
print(f"   2026 Total (all roads): {total_2026:.0f} crashes")
print(f"   Year-over-year change:  {yoy_chg:+.1f}%")

print(f"\n5. SAFETY TREND SUMMARY (Crash Rate per 100k AADT):")
improving = [r for r, d in crash_rate_predictions.items()
             if ((d['forecast'].mean() - d['historical'][-12:].mean()) / d['historical'][-12:].mean()) < 0]
worsening = [r for r in crash_rate_predictions if r not in improving]
print(f"   Roads with IMPROVING safety: {', '.join(improving) if improving else 'None'}")
print(f"   Roads with WORSENING safety: {', '.join(worsening) if worsening else 'None'}")

print("\n" + "=" * 80)
print("✓ Complete analysis finished!")
print("=" * 80)
